name: Deploy Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create FTP Test File
        run: |
          echo "FTP TEST $(date)" > dist/apps/web/client/ftp-test.txt ;